### PR TITLE
Add link to JSONiq implementation for Rumble.

### PR DESCRIPTION
**Pull request by ingomueller-net**

### CODE REVIEW

**Comment by ingomueller-net** [comment]
@masonproffitt Are you still working on this project?

**Comment by masonproffitt** [comment]
> @masonproffitt Are you still working on this project?

I still monitor it, yes. Sorry for the delayed response.

Thanks for this! It seems like a nice addition to the list, although I do have a couple comments:

The first is that the repository that you've made is not the easiest to mentally parse very quickly; it took me quite a while to figure out where the implementations of the benchmarks actually are. I mean, the `query` directory is obvious, but I had to read most of the `README` to figure out that `i-1` and `o-1` refer to two different implementations of the first benchmark. I would suggest putting all the `i-` examples in a directory named like `index-based` or something (and similarly for the `o-` examples). I think the lack of plots is another thing that makes it hard to understand what's going on. Are the `ref-*.csv` files some way of writing the histograms? There's no explanation, so I have no idea how to interpret those files.

My other comment is about the actual table entry in the pull request. The analysis description language being demonstrated here is presumably JSONiq, but there's no description of what that is in your entry (I've never heard of it before).

**Comment by ingomueller-net** [comment]
Thanks a lot for the feedback! I just pushed a slightly more detailed description. Do you think that's better?

I have also addressed your feedback on the folder structure and added plots. (The test script generates them if the `--plot-histogram` flag is set.) To answer your question: yes, the `ref-*csv` files are the reference results for various sample sizes. The `--freeze-result` flag allows to overwrite/create the reference results; otherwise, the query result is compared with the reference result. I have used small samples to speed up testing and development.

**Comment by ingomueller-net** [comment]
@masonproffitt: Did you have time to look at the new version of the MR?

**Comment by masonproffitt** [comment]
Yep, yep, I've looked at it now. Sorry, didn't get a chance to get to this before the holiday break. I made one small change since I think it was a typo, but this looks good to me now!

**Review by masonproffitt — APPROVED** [review]

**Comment by ingomueller-net** [comment]
Awesome, thanks! Yes, that was a typo -- well spotted!

**Pull request merged**
