### PR TITLE
Add link to bamboo implementation

### PR DESCRIPTION
**Pull request by pieterdavid**
I put all the benchmarks together in one module for readability, but which ones are run is configurable through a command-line argument.
Please let me know if I misunderstood something (e.g. I saw that the different implementations do not use the same definition of "pt of the trijet system" and MT), or if you need any more information.

### CODE REVIEW

**Comment by masonproffitt** [comment]
Nice! I think it would actually be more readable if they were each in a separate file, though, and that would also be consistent with the other implementations. Could you also add the plot images that you get from your code?

**Comment by pieterdavid** [comment]
Sorry for the delay, I put the benchmarks in a separate repository, one per file, and with the resulting png plot images.

**Comment by masonproffitt** [comment]
Thanks! The plot for 8 seems to be missing though?

**Comment by pieterdavid** [comment]
Indeed, there was a small bug (missing import, fixed in the latest version), thanks for checking, and sorry for the delay.

**Comment by masonproffitt** [comment]
Thanks! I think this is ready to be added now.

**Review by masonproffitt — APPROVED** [review]

**Pull request merged**
