### PR TITLE
Update description of ana -> queryosity

### PR DESCRIPTION
**Pull request by taehyounpark**
"ana" -> "queryosity" (library name change)
"Columnar" -> "Declarative" (non-SIMD)

### CODE REVIEW

**Comment by taehyounpark** [comment]
Hi @masonproffitt I just wanted to ping you so this can be updated

**Comment by masonproffitt** [comment]
Hmm, the second link (https://taehyounpark.github.io/queryosity/) doesn't work for me. I get a 404 error.

**Comment by taehyounpark** [comment]
Hi @masonproffitt, thanks for catching that (the documentation was moved from github repos to readthedocs). I've fixed the link, and everything should be good to go now!

**Comment by masonproffitt** [comment]
Thanks!

**Pull request merged**
